categorias = {
    1: 'Activos',
    2: 'Pasivos',
    3: 'Patrimonio',
    4: 'Costos/Gastos',
    5: 'Ingresos',
}

cuentas_contables = {
    1: {
        10: ('Efectivo y equivalentes de efectivo', 1),
        11: ('Inversiones financieras', 1),
        12: ('Cuentas por cobrar comerciales – terceros', 1),
        13: ('Cuentas por cobrar comerciales – relacionadas', 1),
        14: ('Cuentas por cobrar al personal, accionistas y directores', 1),
        16: ('Cuentas por cobrar diversas – terceros', 1),
        17: ('Cuentas por cobrar diversas – relacionadas', 1),
        18: ('Servicios y otros contratados por anticipado', 1),
        19: ('Estimación de cuentas de cobranza dudosa', 1),
        20: ('Mercaderías', 1),
        21: ('Productos terminados', 1),
        22: ('Subproductos, desechos y desperdicios', 1),
        23: ('Productos en proceso', 1),
        24: ('Materias primas', 1),
        25: ('Materiales auxiliares, suministros y repuestos', 1),
        26: ('Envases y embalajes', 1),
        27: ('Activos no corrientes mantenidos para la venta', 1),
        28: ('Existencias por recibir', 1),
        29: ('Desvalorización de existencias', 1),
        30: ('Inversiones mobiliarias', 1),
        31: ('Propiedades de inversión', 1),
        32: ('Activos por derecho de uso', 1),
        33: ('Propiedad, planta y equipo', 1),
        34: ('Intangibles', 1),
        35: ('Activos biológicos', 1),
        36: ('Desvalorización de activo inmovilizado', 1),
        37: ('Activo diferido', 1),
        38: ('Otros activos', 1),
        39: ('Depreciación y amortización acumulados', 1),
    },
    2: {
        40: ('Tributos y aportes por pagar', 2),
        41: ('Remuneraciones y participaciones por pagar', 2),
        42: ('Cuentas por pagar comerciales - terceros', 2),
        43: ('Cuentas por pagar comerciales - relacionadas', 2),
        44: ('Cuentas por pagar a los accionistas y directores', 2),
        45: ('Obligaciones financieras', 2),
        46: ('Cuentas por pagar diversas – terceros', 2),
        47: ('Cuentas por pagar diversas – relacionadas', 2),
        48: ('Provisiones', 2),
        49: ('Pasivo diferido', 2),
    },
    3: {
        50: ('Capital',  3),
        51: ('Acciones de inversión', 3),
        52: ('Capital adicional', 3),
        56: ('Resultados no realizados', 3),
        57: ('Excedente de revaluación', 3),
        58: ('Reservas', 3),
        59: ('Resultados acumulados', 3),
    },
    4: {
        60: ('Compras', 4),
        61: ('Variación de existencias', 4),
        62: ('Gastos de personal, directores y gerentes', 4),
        63: ('Gastos de servicios prestados por terceros', 4),
        64: ('Gastos por tributos', 4),
        65: ('Otros gastos de gestión', 4),
        66: ('Pérdida por medición de activos no financieros', 4),
        67: ('Gastos financieros', 4),
        68: ('Valuación y deterioro de activos y provisiones', 4),
        69: ('Costo de ventas', 4),
        90: ('Cuentas de control', 4),
        91: ('Costos por distribuir', 4),
        92: ('Costos de producción', 4),
        93: ('Centros de costos', 4),
        94: ('Gastos administrativos', 4),
        95: ('Gastos de ventas', 4),
        96: ('Costos de servicios', 4),
        97: ('Costos financieros', 4),
    },
    5: {
        70: ('Ventas', 5),
        71: ('Variación de la producción almacenada', 5),
        72: ('Producción de activo inmovilizado', 5),
        73: ('Descuentos, rebajas y bonificaciones obtenidos', 5),
        74: ('Descuentos, rebajas y bonificaciones concedidos', 5),
        75: ('Otros ingresos de gestión', 5),
        76: ('Ganancia por medición de activos no financieros', 5),
        77: ('Ingresos financieros', 5),
        78: ('Cargas cubiertas por provisiones', 5),
        79: ('Cargas imputables a cuentas de costos y gastos', 5),
        80: ('Margen comercial', 5),
        81: ('Producción del ejercicio', 5),
        82: ('Valor agregado', 5),
        83: ('Excedente bruto de explotación', 5),
        84: ('Resultado de explotación', 5),
        85: ('Resultado antes de participaciones e impuestos', 5),
        88: ('Impuesto a la renta', 5),
        89: ('Determinación del resultado del ejercicio', 5),
    },
}
